//
//  DataProvider.swift
//  TinyDetails
//
//  Created by Sergey Telnov on 07/04/2025.
//

import Foundation

struct PaintingObject {
    let idPainting: UUID
    let paintingFile: String
    let paintingTitle: String
    let painter: String
    let creationDate: String
    let endSubtitle: String
    let endDescription: String
    let areas: [ClickableArea]
}

struct ClickableArea {
    let idArea: UUID
    let size: CGFloat
    let xPercent: CGFloat
    let yPercent: CGFloat
    let hintText: String
}

struct ResultObject {
    let id: UUID
    let title: String
    var wasClicked: Bool
}

final class DataProvider {
    
    static let shared = DataProvider()
    private init() { }
    
    let paintingList =
    [PaintingObject(idPainting: UUID(),
                    paintingFile: "CreationOfAdam",
                    paintingTitle: "Сотворение Адама",
                    painter: "Микеланджело Буонарроти",
                    creationDate: "circa 1511",
                    endSubtitle: "Вы прошли уровень 'Сотворение Адама'",
                    endDescription: "Фреска является четвёртой из девяти центральных композиций потолка Сикстинской капеллы, посвящённых девяти сюжетам книги Бытия. Фреска иллюстрирует эпизод: 'И сотворил Бог человека по образу Своему'.",
                    areas: [ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 63.41,
                                          yPercent: 34.98,
                                          hintText: "Бог"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 10.08,
                                          yPercent: 54.61,
                                          hintText: "Адам"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 37.98,
                                          yPercent: 46.42,
                                          hintText: "Соприкосновение"),
                    ]),
     PaintingObject(idPainting: UUID(),
                    paintingFile: "Scream",
                    paintingTitle: "Крик",
                    painter: "Эдвард Мунк",
                    creationDate: "1893",
                    endSubtitle: "Теперь у 'Крика' нет никаких секретов от вас",
                    endDescription: "«Крик» как эмблема экспрессионизма служит своего рода прелюдией к искусству XX века, предвещая ключевые для модернизма темы одиночества, отчаяния и отчуждения.",
                    areas: [ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 52.71,
                                          yPercent: 61.13,
                                          hintText: "А-а-а-а"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 5.66,
                                          yPercent: 38.38,
                                          hintText: "Какая-то пара следует за мной"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 35.58,
                                          yPercent: 37.23,
                                          hintText: "Это лодки на фоне?"),
                    ]),
     PaintingObject(idPainting: UUID(),
                    paintingFile: "MonaLisa",
                    paintingTitle: "Мона Лиза",
                    painter: "Леонардо да Винчи",
                    creationDate: "circa 1503",
                    endSubtitle: "Вы разгадали все загадки 'Джоконды'",
                    endDescription: "Картина Леонардо да Винчи, одно из самых известных произведений живописи. Считается, что на картине изображена Лиза Герардини, супруга флорентийского торговца шёлком Франческо дель Джокондо. Картина Леонардо да Винчи, одно из самых известных произведений живописи. Считается, что на картине изображена Лиза Герардини, супруга флорентийского торговца шёлком Франческо дель Джокондо.",
                    areas: [ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 44.88,
                                          yPercent: 31.31,
                                          hintText: "Эту деталь моего лица считают наиболее таинственной."),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 50.85,
                                          yPercent: 21.34,
                                          hintText: "А куда делись мои брови?"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 39.46,
                                          yPercent: 82.61,
                                          hintText: "Нет украшений. Не замужем?"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 46.05,
                                          yPercent: 13.5,
                                          hintText: "Вуаль на голове? Это элегантно!"),
                    ]),
     PaintingObject(idPainting: UUID(),
                    paintingFile: "GreatWaveOffKanagawa",
                    paintingTitle: "Большая волна в Канагаве",
                    painter: "Кацусика Хокусай",
                    creationDate: "circa 1831",
                    endSubtitle: "Вы прошли уровень 'Большой волны'",
                    endDescription: "Гравюра на дереве, первое произведение из серии «Тридцать шесть видов Фудзи». Считается одним из самых знаменитых и самых популярных произведений японского изобразительного искусства за пределами самой Японии. Некоторые полагают, что на Западе эта гравюра известна лучше, чем любое другое произведение азиатского искусства в целом.",
                    areas: [ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 37.6,
                                          yPercent: 28.76,
                                          hintText: "Главная героиня картины"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 64.19,
                                          yPercent: 70.0,
                                          hintText: "На фоне знаменитая японская гора"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 35.19,
                                          yPercent: 65.06,
                                          hintText: "Эта волна повторяет контур горы на фоне"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 75.5,
                                          yPercent: 90.34,
                                          hintText: "Несчастные рыбаки 1"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 85.04,
                                          yPercent: 63.26,
                                          hintText: "Несчастные рыбаки 2"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 4.88,
                                          yPercent: 21.8,
                                          hintText: "Подпись (надпись)"),
                    ]),
     PaintingObject(idPainting: UUID(),
                    paintingFile: "CoronationOfNapoleon",
                    paintingTitle: "Коронация Наполеона",
                    painter: "Жак Луи Давид",
                    creationDate: "1808",
                    endSubtitle: "Вы прошли уровень 'Наполеона'",
                    endDescription: "Картина французского художника Жака Луи Давида, созданная по заказу императора Франции Наполеона I и изображающая эпизод его коронации, произошедшей 2 декабря 1804 года в соборе Парижской Богоматери. Матери Наполеона не было на его коронации, однако при заказе картины император попросил Давида изобразить её в самом центре.",
                    areas: [ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 45.35,
                                          yPercent: 54.59,
                                          hintText: "Что-то про мамку Наполеона"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 59.07,
                                          yPercent: 61.91,
                                          hintText: "Что-то про Наполеона"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 49.83,
                                          yPercent: 74.69,
                                          hintText: "Что-то про жену"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 69.46,
                                          yPercent: 52.11,
                                          hintText: "Говорят, что я чрезвычайно похож на Джорджа Вашингтона"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 64.88,
                                          yPercent: 61.04,
                                          hintText: "Возможно я один из самых бородатых людей на этой церемонии"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 76.59,
                                          yPercent: 61.54,
                                          hintText: "Да, этой тростью можно отбивать пятерки"),
                    ]),
     PaintingObject(idPainting: UUID(),
                    paintingFile: "HuntersInTheSnow",
                    paintingTitle: "Охотники на снегу",
                    painter: "Питер Брейгель Старший",
                    creationDate: "1565",
                    endSubtitle: "Вы прошли уровень 'Охотников'",
                    endDescription: "Картина написана маслом по дереву в 1565 году. Является частью цикла из шести картин, изображавших времена года, в котором соответствует декабрю-январю. Картина находится в собрании Музея истории искусств в Вене.",
                    areas: [ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 76.82,
                                          yPercent: 57.3,
                                          hintText: "Мы три друга - не разлей вода"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 17.67,
                                          yPercent: 93.57,
                                          hintText: "Эта собака ломает четвертую стену"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 69.15,
                                          yPercent: 60.46,
                                          hintText: "Это командная игра, но мне и одному нормально"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 27.05,
                                          yPercent: 63.62,
                                          hintText: "Про охотников"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 4.11,
                                          yPercent: 62.2,
                                          hintText: "Это мой любимый стол, не хочу, чтобы он повредился"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 40.7,
                                          yPercent: 68.52,
                                          hintText: "Я самый незаметный из трех коллег, но я впереди"),
                            ClickableArea(idArea: UUID(),
                                          size: 30,
                                          xPercent: 84.73,
                                          yPercent: 94.88,
                                          hintText: "Этот водитель убера подъезжает к мосту"),
                    ]),
    ]
}
